### ISSUE TITLE
Enhancment: More Links in Mail?

### ISSUE THREAD

**Issue by ruebyi** [dmpop/little-backup-box#100]
Hi,

I'm quiet sure it's just a small command, but I'm not able to add it my self... 

I just thought it would be great to get not only one Link to the WebUI in the HTML Mail, but also the Link for Upload, FTP and Fileserver - it would be much faster just to click those links than adding the Port manually.

**Comment by dmpop** [comment]
Good idea! I'll add it to my list. :-)

**Comment by ruebyi** [comment]
After Trying Mejiro - perhaps it would be possible to choose the needed adresses in the settings? Or put them there yourself?

**Comment by dmpop** [comment]
Stefan has already added the **Files** link to the wb UI, and I think he's already working on including Mejiro.

**Comment by stefans73** [comment]
Hello,

yes, I hope to find time to test my changes later and push them tonight.

Stefan

Am 30. Juli 2021 11:13:10 MESZ schrieb Dmitri Popov ***@***.***>:
>Stefan has already added the **Files** link to the wb UI, and I think he's already working on including Mejiro.
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/dmpop/little-backup-box/issues/100#issuecomment-889757035
-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.

**Comment by stefans73** [comment]
done
