### ISSUE TITLE
Getting going

### ISSUE THREAD

**Issue by jamiek0326** [dmpop/little-backup-box#11]
I ran the script on my Pi and it seems to not be working. The read light will blink on my card reader and then after a period of time, the Pi shuts down. Im using a Canon 5D Mark 3 CF card and either a USB 128gb stick or Seagate 4tb drive. Is there any way to have the process run in a terminal window or something to see what the current task is that is running to determine the failing point? Im not really well versed in the entire Raspberry Pi eco system so I may be missing something completely but It would be nice to see what is going on and if I can fix this. Running Raspian NOOBs on the Pi

**Comment by dmpop** [comment]
You might want to check the *little-backup-box.log* file in the home directory for clues.
