### ISSUE TITLE
Delete Log

### ISSUE THREAD

**Issue by thelightdecides** [dmpop/little-backup-box#112]
Hi,
the "Delete Log" button in the webinterface does not delete the file, it is still there.

Best regards
Thomas

**Comment by dmpop** [comment]
Good grief! This thing just doesn't want to be fixed. Anyway, it's fixed in 5cd7b7fbfe0897564b206700f01cb0a05d6165c3 At least I think it's fixed. :-) Thank you for reporting the issue. I'd be grateful if you could try the fixed version and report back. Thank you!

**Comment by thelightdecides** [comment]
Works fine now! Thank you!
