### ISSUE TITLE
Wifi file sharing - not an issue but I'd like help

### ISSUE THREAD

**Issue by lucasault** [dmpop/little-backup-box#13]
Hey, do you guys think that there is a way to modify this program so that you could also stream files stored on the backup memory device to computers and phones? I'm a massive noob when it comes to linux programming, i really need to take the time to learn it.  If anyone could help figure this out it would be much appreciated.

**Comment by johnelliott** [comment]
I think the DLNA server is for that. I am just checking this out tonight.

**Comment by dmpop** [comment]
Little Backup Box does this already: miniDLNA is installed and configured by the installer script.

**Comment by lucasault** [comment]
@dmpop okay, I thought i read that, how does one go about using it?
