### ISSUE TITLE
Installer error check

### ISSUE THREAD

**Issue by dmpop** [dmpop/little-backup-box#26]
Check whether all the required packages have been installed before continuing the installation.

**Comment by aadithyarulez** [comment]
Having a look at the install script, these seem to be the packages required : acl git-core screen rsync exfat-fuse exfat-utils ntfs-3g gphoto2 libimage-exiftool-perl dialog python3-pip bottle. Correct me if I'm wrong.

**Comment by Curtis777** [comment]
all installed still troubles to get it running
