### ISSUE TITLE
SSH connection not possible after everything is installed

### ISSUE THREAD

**Issue by akrizski** [dmpop/little-backup-box#32]
Hardware:
Rasberry Pi 2 Model B V1.1

OS:
RASPBIAN STRETCH WITH DESKTOP
Version:April 2018
Release date:2018-04-18
Kernel version:4.14

So I installed the OS on a microSD card, started an SSH connection (over LAN and later over a Wifi-Dongle), updated everything and finally installed the little-backup-box.
I chose the "card backup"-function and tested it. Everything works fine.

But now I am not able to make a new SSH connection. I am on the login console and if I am writing a wrong password, it just says access denied and I can try again. But if I write the right password, i get the following message:

"server unexpectedly closed network connection"

Is this because of the function to backup? It dosn't allow anything other than a card reader or a usb device?
Is it maybe possible to not let it shutdown after 5 minutes of not detecting any sorce and destination drive? So that after 5 minutes the backup function just exits and the raspi works like without the "little-backup-box"? If not then I have to reformat the sd card with a fresh OS to be able to update new functions or install something else?

(Please note that I am a total beginner Linux and Raspi, so maybe I am missing something or don't understand some functionalities right)

**Comment by dmpop** [comment]
Little Backup Box has nothing to do with SSH. Something else is causing the problem.
