### ISSUE TITLE
Process complete?

### ISSUE THREAD

**Issue by Hofstad** [dmpop/little-backup-box#34]
Hi I dont know if this is the correct place to ask. 
I was looking for a script for raspberry like little-backup. But its lacking some features to fully trust it on the go

Is it possible you can add?
- A LED(s) or a smal Oled screen to show the file transfer i % until its done
- Set the Pi in Wifi AP (Access point) for easy control of the device from a android device. For checking what is connected, check the file transfer progress and maybe access the media on the drive.

I dont know if you have time for this but is just a thought

**Comment by slimline33** [comment]
Something like this oled would be very nice: https://www.banggood.com/1_3-Inch-4Pin-White-OLED-LCD-Display-12864-IIC-I2C-Interface-Module-For-Arduino-p-1067874.html?p=EX0216559147201405VP

If someone can make  the code I will provide the oled

**Comment by slimline33** [comment]
Now I added a buzzer on gpio8 for a short signal when ready.

https://www.raspberrypi-spy.co.uk/berryclip-6-led-add-on-board/berryclip-6-led-add-on-board-instructions/

**Comment by slimline33** [comment]
Acutally I'm working on a case for the "CopyPi". A OLED would be nice, but the buzzer is ok. I will use it with a ssd and some sort of 18650 batteries for taking it away 🥇 

![image](https://user-images.githubusercontent.com/3323812/43662936-d94fd55e-9767-11e8-92d8-9d8a84ec63b7.png)

**Comment by jroblesruiz** [comment]
@slimline33 I would like to colaborate, I was interested in doing something similar. I have an oled display like that. But It would be great if you share what kind of borad and battery are you using?

**Comment by JAN4GER** [comment]
any progress of adding buzzer or oled screen features?

also: how to stop the script while I do not want to use it?
for example when none card in usb, I would like to use Rasbian as usual, but actually your script force reboot after severa seconds.

**Comment by shunstad** [comment]
This is more or less the only thing missing from my «pidrop» at the moment, so this would be a welcome feature. While the copy of files usually go without any problems, I would love to get some sort of file verification and an alert of some kind, or even an email with the verfication log, just to be sure that the copy has been completed.

**Comment by slimline33** [comment]
Sorry for my late comment. I'm not getting mail notification from github. I will check this tomorrow.

**Comment by dmpop** [comment]
The latest version of Little Backup Box introduces experimental support for SSD1306-based 128x32 OLED display.

**Comment by Austinthemighty** [comment]
For the oled screen is that over i2c or SPI ?

**Comment by dmpop** [comment]
> For the oled screen is that over i2c or SPI ?

I2C

**Comment by MilzaOnTwitch** [comment]
I m interested as well and i line to collaborate as well. I wantet to do the same, with display and contactable app.

**Comment by dmpop** [comment]
Closing, because I started working on implementing a progress indicator.
