### ISSUE TITLE
Do file systems affect functionality? 

### ISSUE THREAD

**Issue by sallan84** [dmpop/little-backup-box#35]
I am using an sd card through a card reader and fat32 formatted usb stick, but not having any luck getting this to work. I have checked the SDA assignments and it seems the USB card is always mounted as SDA1 but the SD card is mounted as either SDC1 or SDD1, which of course renders the code inoperable. I've tested this a lot and getting the same problems. 

Any help greatly appreciated, I really want to get this up and running!

**Comment by dmpop** [comment]
LIttle Backup Box works with FAT32, exFAT, NTFS, and all popular Linux filesystems. OK, in case the USB stick is mounted as SDA1 and the SD card is mounted as SDC1, open the *card-backup.sh* script and edit the following lines:

```
STORAGE_DEV="sda1" # Name of the storage device
CARD_DEV="sdb1"
```
This should do the trick. Also, are you using Raspbian Lite or regular Raspbian with the Pixel desktop?

**Comment by sallan84** [comment]
I am using raspbian with the pixel desktop. I meant that in one instance, the card mounts ad Sdc1, then the next try after rebooting and starting the process again, it mounts as SDD1, and it is inconsistent, is this to do with using the pixel desktop? Sorry to ask so many questions! !

**Comment by dmpop** [comment]
Ah, that explains it! You should use Rasbian Lite. It comes without a desktop environment, and it mounts storage devices where Little Backup Box expects them. I need to update the README file to reflect that.

**Comment by sallan84** [comment]
Ahh amazing!! I will do that!!
