### ISSUE TITLE
rsync error at line 68 in card backup script

### ISSUE THREAD

**Issue by sallan84** [dmpop/little-backup-box#36]
Hi, me again! So I am now running the little backup box in raspbian lite, it seems to work, no crashes and it transferred the first card just fine, but when I tried to transfer another card i got this error, and then when I tried to transfer the first card but with more images on it I got the same error: 

/home/pi/little-backup-box/scripts/card-backup.sh: line 68[: 201805301529-30707.id: binary operator expected rsnc error: some files/attrs were not transferred (see previous errors) (code 23) at main.c(1196) [sender=3.1.2]

any help with this greatly appreciated.

**Comment by dmpop** [comment]
I have no clue what causes the error.

**Comment by JohnJocoo** [comment]
Hi, sorry for writing to closed issue, but I stamped upon the same problem while debugging card-backup to some old FAT32 flash stick. The reason in that in some undefined scenarios little-backup-box can create more than one .id file in the card. After all attempts to do backup from such card (2 or more .id files) will fail with error above. I have not found the way to reproduce two .id files creation scenario thought.
