### ISSUE TITLE
Leds control on other boards

### ISSUE THREAD

**Issue by Yury-MonZon** [dmpop/little-backup-box#4]
Would you mind adding some config to use another boards leds?
For Orange Pi you can use sudo sh -c "echo heartbeat > /sys/class/leds/red_led/trigger"
or
sudo sh -c "echo heartbeat > /sys/class/leds/green_led/trigger"

I've checked your code against it - everything works if you change the path.

Thanks!

**Comment by dmpop** [comment]
Thanks! Feel free to add improve the script and submit a pull request.
