### ISSUE TITLE
Using UUID for bomb-proof mounting

### ISSUE THREAD

**Issue by cyclist-obscura** [dmpop/little-backup-box#41]
I've had some issues in the past with SD cards and USB storage not always appearing with the same device ID (/dev/sda /devsdb etc/) which in turn prevents the backup from running.

Is there a possibility of using a list of known UUIDs to ensure that your disks mount in the correct place?

**Comment by dmpop** [comment]
Yes, it's possible. But this can only be done manually, and the process requires working knowledge of Linux. Since Little Backup Box is designed first and foremost for photographers, I'm reluctant to introduce this level of complexity.
