### ISSUE TITLE
Enable/disable on demand

### ISSUE THREAD

**Issue by erenkoff** [dmpop/little-backup-box#46]
I am new to this so please forgive me if I am asking simple questions.  I will be using my Raspberry Pi with little-backup-box to automatically copy my pictures to a storage device without a monitor/keyboard, but I would also like to use it on other occasions for other purposes.  Is there any way to disable the scripts so that they will not run until such time as I know that I am going on a trip and then enable them before the start of the trip...and again disable them when I get back?

**Comment by dmpop** [comment]
Please post your question at https://discuss.pixls.us/c/hardware/little-backup-box

**Comment by erenkoff** [comment]
Thanks. Done
