### ISSUE TITLE
Shortened URL for uninstall script gives 404

### ISSUE THREAD

**Issue by pvtshdw** [dmpop/little-backup-box#66]
Just a quick note that the shortened URL for the uninstall script (https://is.gd/unlittlebackupbox) gives a 404.  I found the uninstall script in the install directory (~/little-backup-box/uninstall-little-backup-box.sh), so no worries.  The URL is in the "Little Backup Book" as well.

Fantastic work!  Thank you so very much!

**Comment by dmpop** [comment]
Fixed! Thank you so much for reporting the issue!
