### ISSUE TITLE
Installation failed when user is not "pi"

### ISSUE THREAD

**Issue by ctschach** [dmpop/little-backup-box#68]
Okay, I tried to install LBB on a fresh Buster image. The only change I did was changing the "pi" user to my preferred one. The use itself works fine. It can sudo without an password and has a proper home directory.

However, the installation failed. I haven't tracked down the issue, but some config-files uses a static used instead of the user you get with "id".

**Comment by dmpop** [comment]
A brief description of how to install Little Backup Box with a different user is available in the _Little Backup Book_.
