### ISSUE TITLE
pi zero script issue

### ISSUE THREAD

**Issue by vipergts4509** [dmpop/little-backup-box#69]
having an issue.... when i run the script both on diet pi and raspi os (latest lite img )at the olded display option if i select no my pi reeboots (installing via ssh ) if i select yes it just says  enable i2c and reboot it never finishes the installation tried on a 400gb and a 256gb high endurence card both has the same issue . (install choice is internal)

**Comment by dmpop** [comment]
> it never finishes the installation

How do you know that? Do you get any error messages? Something doesn't work as expected?
