### ISSUE TITLE
can't get it to work

### ISSUE THREAD

**Issue by handyt2** [dmpop/little-backup-box#7]
I am new to Raspberry pi. 
I set this up on RPi W with Zero4U hub (OS: Raspbian Jessie Lite.)
it boots & stuck on login prompt.
I tried inserting usb stick, and memory card. Nothing was written.
how to diagnose?
how can I disable little-backup-box upon startup?
thanx

**Comment by airgiraffe** [comment]
HI handyt2, I have a similar problem with the same gear. Have you attached the ferrite ring that should have come with the Zero4U hub?
