### ISSUE TITLE
Camera backup cron not working on reboot

### ISSUE THREAD

**Issue by MobiuSRIT** [dmpop/little-backup-box#71]
I had an issue where the camera-backup script wasn't automatically backing up on a reboot.  Manual executions of the script or clicking the button on the web GUI worked fine.

I saw the cron job was:
@reboot sudo /home/pi/little-backup-box/scripts/camera-backup.sh >> /home/pi/

due to the install script having:
    
 crontab -l | {
                cat
                echo "@reboot sudo /home/"$USER"/little-backup-box/scripts/camera-backup.sh &gt;&gt; /home/"$USER"/"
            } | crontab
            ;;

Executing that manually, gives:
pi@pi-lbb:~ $ sudo /home/pi/little-backup-box/scripts/camera-backup.sh >> /home/pi/
-bash: /home/pi/: Is a directory

I removed the ">> /home/pi" and things are working.  
What am I missing about how this is set up?

**Comment by dmpop** [comment]
Fixed in 6d3189afff6ec96b964d8a254397ca0d93588065 Thank you for reporting the issue!
