### ISSUE TITLE
ingest multiple SD cards?

### ISSUE THREAD

**Issue by rlanyi** [dmpop/little-backup-box#72]
Hi,

thanks for this great tool! I've a specific scenario where the RPI would be always on, multiple USB card readers would be connected to it and it would backup them automatically to a NAS.

Our team creates videos with multiple cameras in HD on events. When the event is over, it takes a long time to backup 8-10 SD cards. If we'd buy e.g. 4 pcs of USB card readers, then it could be done in 2-3 batches and we wouldn't have to wait for the last one to finish. Also there is no need to shutdown the RPi in this scenario.

Questions:
1. How hard would it be to modify LBB to support this?
2. Has the latest RPi the bandwidth to support this kind of operation?

Thanks in advance!

**Comment by dmpop** [comment]
Hello,

There is a fork that does something similar: https://github.com/nickelsound/little-backup-box I haven't tried it myself, though. You need to contact the fork's maintainer. They might be able to answer your second question. :-)
