### ISSUE TITLE
when both card reader and usb drive are plugged in, the pi shuts down in 5 seconds

### ISSUE THREAD

**Issue by dbenyakar** [dmpop/little-backup-box#8]
Hi
I followed the instructions in your book and setup the RPi3.
When I connect the USB backup device (WD passport) the led blinks slowly. When I connect the card reader with the card in it, the leds start blinking for few seconds (3-5 seconds) then the Pi shuts down.
It only created the CARD_ID folder and nothing else.
What can be the issue?
Should I use a certain type of card reader? or backup storage USB device?
Regards

**Comment by dmpop** [comment]
Most likely a power issue. Try to connect the hard drive via a powered USB hub. Officially, though, Little Backup Box is designed to work with USB keys as backup devices.
