### ISSUE TITLE
Add function camera to storage and unite all backup-scripts in one

### ISSUE THREAD

**Issue by stefans73** [dmpop/little-backup-box#85]
Would be nice to have all the four possibilities:

- Backup storage (memory-card) to external storage
- Backup storage (memory-card) to internal storage
- Backup camera to external storage
- Backup camera to internal storage

That's my next target. To reach this without creating another file to maintain, I want to unite all the single backup-scripts in one. This backup.sh will be started with arguments.

**Comment by dmpop** [comment]
I'm really interested to see what you come up with. But to be honest, I prefer to have separate scripts for each backup type. They are easier to maintain, and it's easier to add new scripts if necessary. That said, I may change my mind when I see your result. :-)

**Comment by stefans73** [comment]
Hi Dimitri,

please just have a look at the pull request following. I had some 
trouble in changes I had do do in every script. Sometimes I did minor 
mistakes in sequence, sometimes I had to rename variables and forgot one 
- nasty things like that. Because I would like to create the 
self-refreshing log-area inside the web-UI, I expect a lot more basic 
changes with a ton of chances for errors.

I'll do some final tests and push it. If you want to test it, please run 
change-mode.sh to get the correct crontab-entry. Everything should also 
run via web-UI.

Thank you,
Stefan

---
Mit meinem angefügten öffentlichen Schlüssel "0xE61B756E.asc" können Sie 
gerne verschlüsselte Mails an mich senden. Näheres auch unter 
https://www.gpg4win.de/

Am 2021-07-11 16:29, schrieb Dmitri Popov:

> I'm really interested to see what you come up with. But to be honest, I 
> prefer to have separate scripts for each backup type. They are easier 
> to maintain, and it's easier to add new scripts if necessary. That 
> said, I may change my mind when I see your result. :-)
> 
> --
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub [1], or unsubscribe 
> [2].


Links:
------
[1] 
https://github.com/dmpop/little-backup-box/issues/85#issuecomment-877809559
[2]
