### ISSUE TITLE
IP not displayed correctly after installing comitup

### ISSUE THREAD

**Issue by ruebyi** [dmpop/little-backup-box#96]
Hi!

I love your project and got it running very quickly.

But One bug is still there - or I did a mistake:
After installing comitup I won't get the display to show the actual IP. It sticks with 10.42.0.1

Before installing comitup it worked!

Best Tobias

**Comment by dmpop** [comment]
Thanks for reporting the bug. I'll look into it.

**Comment by ruebyi** [comment]
I just played around a bit - I receive the correct Adress via the Mail Notification, but OLED and the Logmonitor show the comitup Adress

**Comment by dmpop** [comment]
Good to know! Thank you for reporting back. :-)

**Comment by ruebyi** [comment]
With the latest fixes it‘s better - it shows the Actual IP on top 

192.168.1.116
LittleBackupBox
10.42.0.1
Ready

**Comment by dmpop** [comment]
Good to know. Thank you for reporting back!
