### ISSUE TITLE
GPIO Button for power off ?

### ISSUE THREAD

**Issue by maelremrem** [dmpop/little-backup-box#98]
Hello 
Can I use the GPIO to trigger the power off script ?
And any idea how to do so ?
Great projet btw (I just have problem with my OLED screen but I suspect is dead, new ones are coming)

**Comment by dmpop** [comment]
Please post general queries on https://discuss.pixls.us/c/hardware/little-backup-box/ This place is for tracking bugs and technical issue. Also thank you for buying the _Little Backup Book_! I think you'll find the answer to your question there. ;-)
