### ISSUE TITLE
OLED Permission denied

### ISSUE THREAD

**Issue by maelremrem** [dmpop/little-backup-box#99]
I have a problem with my oled screen
The OLED won't start but with the i2cdetect -y 1 I can see it (only if I repeat 3 times the command)
It blinks and some of the text appears when I run the status-display.sh
This is the output on the ssh window
![image](https://user-images.githubusercontent.com/11769158/126715547-2718fc66-3c8e-42d1-b443-d8d595f06779.png)

any idea to fix this ?

**Comment by stefans73** [comment]
Did you run status-display.sh as root?

---
Mit meinem angefügten öffentlichen Schlüssel "0xE61B756E.asc" können Sie 
gerne verschlüsselte Mails an mich senden. Näheres auch unter 
https://www.gpg4win.de/

Am 2021-07-23 00:07, schrieb Maelremrem:

> I have a problem with my oled screen
> The OLED won't start but with the i2cdetect -y 1 I can see it (only if 
> I repeat 3 times the command)
> It blinks and some of the text appears when I run the status-display.sh
> This is the output on the ssh window
> [1]
> 
> any idea to fix this ?
> 
> --
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub [2], or unsubscribe 
> [3].


Links:
------
[1] 
https://user-images.githubusercontent.com/11769158/126715547-2718fc66-3c8e-42d1-b443-d8d595f06779.png
[2] https://github.com/dmpop/little-backup-box/issues/99
[3]

**Comment by maelremrem** [comment]
Yes and it's blocked to this :
![image](https://user-images.githubusercontent.com/11769158/126747425-e3e9d209-ea5e-4104-9f9f-7f0e32e0b677.png)
and if I try dos2unix manually, it works to convert but this is what I get : 
![image](https://user-images.githubusercontent.com/11769158/126747511-157c6978-5532-4f46-a709-598302eedf7c.png)

**Comment by maelremrem** [comment]
I made a copy of the status-display.sh script and modified it to comment this : "dos2unix "$CONFIG"
and now this is what I get on the OLED : https://youtube.com/shorts/I-iMOUvJ20Q?feature=share

**Comment by dmpop** [comment]
Maybe it's a good idea to start with some basic troubleshooting first.

Try to run the following commands on the Raspberry Pi:

```
sudo oled r
sudo oled +a "Hello"
sudo oled +b "this"
sudo oled +c "is a"
sudo oled +d "test"
sudo oled s
```

Does it work? Do you see the text on the screen?

**Comment by maelremrem** [comment]
it does nothing. No text on screen and no error on the console
when I do sudo i2cdetect -y 1 this is what I get :
![image](https://user-images.githubusercontent.com/11769158/126754532-f0a53af6-c002-4722-aa6b-75d8807f0aa1.png)
I have to do it 2 times to get an address
I use an RPI3 B+ does it change something ?

**Comment by dmpop** [comment]
If the display shows nothing, and the Raspberry Pi has trouble detecting it (you need to run the detect command twice), it either mean that the display is defective or it's wired incorrectly to the GPIO pins.
